### ISSUE TITLE
Android 12 issues 

### ISSUE THREAD

**Issue by harukayamazaki** [Magisk-Modules-Alt-Repo/ttf-twemoji#1]
Sadly it doesn't work on stock google android 12. I'll see if crdroid 8.1 (lineage os based rom) is compatible

**Comment by harukayamazaki** [comment]
It's not compatible with crdroid 8.1 either :(

**Comment by ez-me** [comment]
That's weird, unless Android 12 changed substantially the way emoji fonts are handled (maybe https://developer.android.com/jetpack/androidx/releases/emoji2 is to blame) the 3 main systems (SBIX, COLR/CPAL and CBDT/CBLC) should work.

The one way that seems to only work on Firefox is SVG.

(source of this info https://wiki.archlinux.org/title/Fonts#Emoji_and_symbols )

**Comment by gudenau** [comment]
I can confirm that replacing the system emoji fonts doesn't work anymore with Android 12 on my Pixel 4 XL running the factory image with Magisk.

I used a file manager to verify that the fonts were being changed.

I have yet to dig deeper into the issue.

**Comment by ez-me** [comment]
I upgraded to Android 12 (LineageOS 19.1) and I don't have a problem with the emoji, after I cleaned the cache and rebooted.

If no other issue with Android 12 is added in this issue, I'm closing it.

**Comment by gudenau** [comment]
What caches?

Edit:
Clearing Gboard caches seems to have fixed it, cool.

**Comment by gudenau** [comment]
Oh individual application caches I suppose.

**Comment by ez-me** [comment]
App cache needed to be cleared.
