### ISSUE TITLE
Invalid readme file name.

### ISSUE THREAD

**Issue by Fox2Code** [Magisk-Modules-Alt-Repo/ttf-twemoji#2]
Current readme is named `readme.md` but it should be named `README.md`.

Because GitHub requests are case sensitive.

**Comment by ez-me** [comment]
Changed the filename to README.MD hope that fixes any github quirks.

**Comment by Fox2Code** [comment]
I added support for `readme.md` on my manager RC build, now I have to add `README.MD` support too...

Well meh, I'm supporting far worse naming cases, supporting weird capitalization in my app won't do any harm.

Don't worry, I will manage case-sensitivity issue on my side.
